export interface Tokens {
    uuid: string ,
      symbol: string,
      name: string,
      color: string,
      iconUrl: string,
      marketCap:number,
      price: number,
      listedAt: number,
      tier: number,
      change: number |string,
      rank: number,
      sparkline: [
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
         string,
      ],
      lowVolume: boolean,
      coinrankingUrl: string,
      hVolume: number,
      btcPrice: number
  }
